{
  "hash": "4461fcbd80ac37ce777fc47417c0d77f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tutorial 3: alternative sampling frame stratification example\"\nauthor: \n  - name: \"Claire Dooley\"\n    affiliation: \"Centre for Advanced Spatial Analysis, University College London\"\n    email: \"c.dooley@ucl.ac.uk\"\nformat: html\neditor: visual\nsuggested-citation: \"Dooley, C.A. (2025). gridEZ Tutorial 3 version 1.0\"\nbibliography: references.bib\n---\n\n**Suggested citation:** {{< meta suggested-citation >}}\n\n## Tutorial Aim\n\nThe aim of this tutorial is to generate and evaluate a bespoke gridded sampling frame for Samoa stratified by administrative units and distance to coast. This tutorial provides guidance on how to create strata that may be very specific to a survey instead of using widely available data such as settlement type. We use distance to coast for this Samoa example but this could just as easily be distance to any points of interest, e.g. health care facilities or railway stations, depending on the aims of the survey for which the sampling frame is being constructed. The gridded sampling frame will contain gridded Enumeration Zones (EZs) that can be used for sampling survey units.\n\n## Packages\n\nLoad all the R packages necessary to complete this tutorial. If you have not yet installed the `gridEZ2` package, please follow the instructions on the Tutorial Overview page.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# list of required packages\nrequired_packages <- c(\"sf\", \"terra\", \"parallel\", \"data.table\", \"ggplot2\", \"scico\", \"patchwork\")\n\n# install missing packages\ninstall.packages(setdiff(required_packages, installed.packages()[, \"Package\"]))\n\n# load packages\nlibrary(sf)\nlibrary(terra)\nlibrary(data.table)\nlibrary(parallel)\nlibrary(ggplot2)\nlibrary(scico)\nlibrary(patchwork)\nlibrary(gridEZ2)\n```\n:::\n\n\n## Datasets\n\nWe need two publicly available datasets: gridded population estimates and administrative boundaries. We'll use the WorldPop population data [@bondarenko2025] and the GADM administraive boundare [@GADM2022] that we also used in the previous tutorials. For more information about the population estimates, please see Tutorial 1. Here, we simply use these datasets without revisiting their details.\n\nAs with the previous Tutorials, we read in datasets from a folder called \"data_wsm\"*.* The code below checks whether you have the folder already. If you don't, the code will create it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check your working directory\ngetwd()\n\n# you may need to change your working directory to point to the location where the data_wsm folder sits. Use setwd() to change your working directory if needed\n\n# check whether the data folder already exists - if not, create the folder \nfile_path <- paste0(getwd(),\"/data_wsm/\")\nif (!dir.exists(paste0(file_path))) {\n  dir.create(file_path)\n}\n```\n:::\n\n\n### Population counts data\n\nYou can read in the data directly from the WorldPop server using Option 1 code snippet or you can download the data via the link below, save it into your \"data_wsm\" folder and then use Option 2 code snippet to read the data into R.\n\n<https://hub.worldpop.org/geodata/summary?id=76095>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Option 1: read in directly from WP server\npopulation_raster <- terra::rast(\"https://data.worldpop.org/GIS/Population/Global_2015_2030/R2025A/2025/WSM/v1/100m/constrained/wsm_pop_2025_CN_100m_R2025A_v1.tif\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Option 2: read in from file after download\npopulation_raster <- terra::rast(paste0(getwd(),\"/data_wsm/wsm_pop_2025_CN_100m_R2025A_v1.tif\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(population_raster,main=\"Population distribution of Samoa (WorldPop data)\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial3_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### Administrative Unit Boundaries\n\nThe GADM boundaries can be downloaded here by selecting Samoa from the drop down and then clicking \"Shapefile\": <https://gadm.org/download_country.html>\n\nAgain, add the unzipped file to your \"data_wsm\" folder. We'll use the level 2 administrative units.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadmin_sf <- sf::st_read(paste0(getwd(),\"/data_WSM/gadm41_WSM_shp/gadm41_WSM_2.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `gadm41_WSM_2' from data source \n  `/Users/clairedooley/Documents/Research/gridEZ/gridEZ_tutorials/data_wsm/gadm41_WSM_shp/gadm41_WSM_2.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 43 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -172.8041 ymin: -14.07722 xmax: -171.3977 ymax: -13.43981\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# look at the list of fields in admin_sf\nnames(admin_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"GID_2\"     \"GID_0\"     \"COUNTRY\"   \"GID_1\"     \"NAME_1\"    \"NL_NAME_1\"\n [7] \"NAME_2\"    \"VARNAME_2\" \"NL_NAME_2\" \"TYPE_2\"    \"ENGTYPE_2\" \"CC_2\"     \n[13] \"HASC_2\"    \"geometry\" \n```\n\n\n:::\n\n```{.r .cell-code}\n# plot the \"GID_2\" field which contains the level 2 unit IDs\nplot(admin_sf[\"GID_2\"],main=\"Level 2 administrative units for Samoa (GADM data)\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial3_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Data Processing\n\nAs with any spatial analysis, the first step is to ensure the CRS of our datasets is the same.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# identify the CRS of the population raster\nr_crs <- terra::crs(population_raster)\n\n# if the strata layers have a different CRS, transform\nif(r_crs !=sf::st_crs(admin_sf)){admin_sf <- sf::st_transform(admin_sf, r_crs)}\n```\n:::\n\n\nNext, we need to convert the sf object containing administrative units into a raster where each grid cell is classified by the level 2 administrative unit they fall within. We do this using the base grid of the population raster.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# rasterize admin_sf\nadmin_raster <- terra::rasterize(admin_sf,population_raster,field=\"GID_2\")\n\n# remove admin_sf object as we no long need it\nrm(admin_sf)\n```\n:::\n\n\nNow we can create our second strata layer - distance to coast. The administrative units raster we just made contains NA values for the sea. We can therefore duplicate this raster and replace any non-NA values with a single value, e.g. 1, to distinguish between land and sea.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a sea raster\nsea_raster <- admin_raster\nvalues(sea_raster) <- ifelse(is.na(values(admin_raster)), 1, NA)\nplot(sea_raster, main=\"Sea around Samoa\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial3_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nBased on this binary raster, we can create a distance to coast raster using the `terra::distance` function. This may take a minute or so to run.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a distance from coast raster\ndist_raster <- terra::distance(sea_raster)\nplot(dist_raster, main=\"Distance to coastline, Samoa\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial3_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nFrom this distance raster we can classify grid cells into bands of distances to create strata. Based on the population and geography of Samoa, we'll use three distance bands. Two would also work. More would end out cutting up the land into quite small areas - remember that we will also stratify by administrative units too. Our bands will be:\n\n-   Band 1: 0–2 km\n\n-   Band 2: 2–5 km\n\n-   Band 3: \\>5 km\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# reclassify into distance bands\n# 0–2 km = band 1, 2–5 km = band 2, >5 km = band 3\nrcl <- matrix(c(\n  0,    2000, 1,\n  2000, 5000, 2,\n  5000, Inf,  3\n), ncol = 3, byrow = TRUE)\ndist_raster <- terra::classify(dist_raster, rcl)\nplot(dist_raster, main=\"Categorized distance to coastline, Samoa\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial3_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nLet's confirm that these bands categories are sensible given the population distribution of Samoa. We do this using the `terra::zonal` function to sum up the population inside each band.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate population in each band to check they are sensible distances\npop_per_band <- terra::zonal(population_raster, dist_raster, fun = \"sum\", na.rm = TRUE)\n# calculate percentage of pop in each band\npop_per_band$perc_total_pop <- round(pop_per_band[,2]/sum(pop_per_band[,2])*100,2)\npop_per_band\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  GID_2 wsm_pop_2025_CN_100m_R2025A_v1 perc_total_pop\n1     0                       128.1908           0.06\n2     1                    157209.1857          71.89\n3     2                     49739.3929          22.74\n4     3                     11608.5353           5.31\n```\n\n\n:::\n:::\n\n\nApproximately 72% of the population falls within 2km of the coastline (band 1) and there is about 23% of the population between 2 and 5kms of the coastline. A small portion (\\~5%) of the population live more than 5km away from the coastline. According to our definition of where the coastline sits, about 128 people live in the sea. This may be due to the way the administrative units are rasterized. If the polygon line of the boundary does not cross the centroid of a grid cell, that grid cell is assumed to be outside of the polygon. In reality, the rasterization step can lead to partially populated grid cells being incorrectly counted as outside the country. This may also occur if the population data and (unrasterized) administrative unit boundaries don't align.\n\nThis mismatch in datasets is a common issue. The datasets can be reviewed to determine whether any real population might be excluded and to decide if additional steps are needed. We cover this in Tutorial X. For now we will continue with the rasters that we have.\n\nThe final step of the data processing is to save the three rasters into a folder called \"made\" inside your \"data_wsm\" folder.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check whether the data folder already exists - if not, create the folder \nfile_path <- paste0(getwd(),\"/data_wsm/made/\")\nif (!dir.exists(paste0(file_path))) {\n  dir.create(file_path)\n}\n\n# save pop and admin rasters if they don't already exist\n# as these rasters are the same as in Tutorial 1, we check whether they exist first and only save if they don't\nif (!file.exists(paste0(file_path,\"adminGADM.tif\"))){\n  terra::writeRaster(admin_raster,paste0(file_path,\"adminGADM.tif\"))\n}\nif (!file.exists(paste0(file_path,\"popWP.tif\"))){\n  terra::writeRaster(population_raster,paste0(file_path,\"popWP.tif\"))\n}\n\n# save the categorized distance to coast raster \nterra::writeRaster(dist_raster,paste0(file_path,\"disttocoast.tif\"))\n```\n:::\n\n\n## gridEZ: sampling frame generation\n\nIn the next chunk of code, we run `gridEZ` to generate a sampling frame consisting of \"large\" EZs and stratified by administrative units and distance to coast categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# clear R environment\nrm(list=ls())\ngc()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          used (Mb) gc trigger  (Mb) limit (Mb) max used  (Mb)\nNcells 1671873 89.3    3078038 164.4         NA  2448298 130.8\nVcells 2531676 19.4   10146329  77.5      36864 10145561  77.5\n```\n\n\n:::\n\n```{.r .cell-code}\n# define number of cores for parallel processing\nprocessing_cores <- max(parallel::detectCores() - 1, 1)\n\n# define input & output file pathways (checking output folders exist & creating them if they don't)\nfile_path_inputs <- paste0(getwd(),\"/data_wsm/made/\")\nfile_path_outputs_tuts <- paste0(getwd(),\"/results_wsm/\")\nif (!dir.exists(paste0(file_path_outputs_tuts))) {\n  dir.create(file_path_outputs_tuts)\n}\nfile_path_outputs <- paste0(getwd(),\"/results_wsm/tutorial3/\")\nif (!dir.exists(paste0(file_path_outputs))) {\n  dir.create(file_path_outputs)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gridEZ code: stratification by level 2 admin units & distance to coast categories\ngridEZ2::gridEZ(population_raster_path  <- paste0(file_path_inputs,\"popWP.tif\"),\n                strata1_raster_path  <- paste0(file_path_inputs,\"adminGADM.tif\"),\n                strata2_raster_path  <- paste0(file_path_inputs,\"disttocoast.tif\"),\n                predefined_EZ_size = TRUE,\n                EZ_target_size = \"large\",\n                output_path = paste0(file_path_outputs),\n                run_ID = \"wsm_wp_large_disttocoast\",\n                ncores=processing_cores)\n```\n:::\n\n\n## Resulting sampling frame\n\n`gridEZ` outputs a table (.csv file) containing EZ level information on population and geographic size and a raster containing the spatial layouts of the EZs. Let's read in the table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in EZs table of your sampling frame \nEZ_tab <- read.csv(paste0(file_path_outputs, \"EZ_Pop_Ncells_wsm_wp_large_disttocoast.csv\"),header=T)\n# number of EZs in your sampling frame\nnrow(EZ_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 336\n```\n\n\n:::\n\n```{.r .cell-code}\n# the first rows\nhead(EZ_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  EZ_ID      pop    N\n1     1 1465.795  444\n2     2 1488.862  307\n3     3 1048.678  132\n4     4 1006.009  301\n5     5  954.669  915\n6     6 1135.277 1509\n```\n\n\n:::\n:::\n\n\nEach row of the table gives information for an individual EZ. There are 336 rows in the table which means there are 336 EZs in the sampling frame. From the top row, we can see that there is an EZ with an ID of 1, a population size of 1466, and contains 444 grid cells.\n\nLet's create a map of the sampling frame. We can plot the raster or we can convert the raster into polygons and map that.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in your sampling frame raster & plot\nEZ <- terra::rast(paste0(file_path_outputs,\"EZ_IDs_wsm_wp_large_disttocoast.tif\"))\n\n# plot raster\ncols <- sample(scico(nrow(EZ_tab)/2, palette = \"broc\"))\nplot(EZ,main=\"Spatial distribution of EZs (raster)\",col=cols)\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial3_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# convert to sf polygons\nres_poly <- terra::as.polygons(EZ, dissolve = TRUE)\nres_poly <- sf::st_as_sf(res_poly)\n# merge the ppolygons and EZ IDs\nres_poly <- merge(res_poly,EZ_tab,by=\"EZ_ID\")\n# plot EZ polygons coloured by EZ IDs\nplot(res_poly[,\"geometry\"],main=\"Spatial distribution of EZs (polygons)\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial3_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n:::\n\n\nThe raster values are the IDs of the EZs. Even with a nice colour palette it can be difficult to distinguish EZs from one another. Converting the raster to EZ polygons makes it easier to see the EZ boundaries.\n\nFrom the shapes of the EZs, we can pick out their alignment with our (categorised) distance to coast strata as well as the administrative units (both mapped above). Success!\n\nLet's map the population and geographic sizes of the EZs to check that they look sensible for \"large\" EZs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot EZ polygons coloured by population per EZ\nplot(res_poly[,\"pop\"],main=\"EZ population size\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial3_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# plot EZ polygons coloured by number of grid cells per EZ\nplot(res_poly[,\"N\"],main=\"EZ grid cells count\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial3_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n:::\n\n\nGenerally, EZ population counts are within a reasonable range of the target EZ population of 1,200 in areas that are not sparsely populated (near the coast) and EZ geographic sizes are close to the maximum of 2,500 grid cells in sparsely populated areas (centre of the main islands).\n\n## Creation of table for survey sample selection\n\nWe can identify the strata that each EZ belong to using the EZ IDs raster along with the two strata rasters. Here, we create a table containing the information from these three rasters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in the strata raster\nadmin_raster <- terra::rast(paste0(file_path_inputs,\"adminGADM.tif\"))\ndist_raster <- terra::rast(paste0(file_path_inputs,\"disttocoast.tif\"))\n\n# create a table of EZ strata values\n\n# ensure the EZ raster has the same extent as the gridEZ input rasters\nEZ <- terra::extend(EZ,admin_raster)\n# we need to create a table with vectors of values in each raster\n# as the admin_raster contains categories, we want the category labels rather than their corresponding numeric value\nadmin_cats <- terra::cats(admin_raster)[[1]]\nadmin_labels <- admin_cats$GID_2[match(admin_raster[], admin_cats$value)]\n# as we defined the distance categories by numeric values, we can directly use those raster values\nEZ_strata <- data.table::data.table(EZ[],\n                                    admin_labels,\n                                    dist_raster[])\n# set column names, change as needed\nnames(EZ_strata) <- c(\"EZ_ID\",\"strata1\",\"strata2\") \n# reduce table down to a single row per EZ\nEZ_strata <- na.omit(EZ_strata)\nEZ_strata <- unique(EZ_strata)\n```\n:::\n\n\nLet's have a look at the top and bottom of the table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# look at the top of the table\nhead(EZ_strata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   EZ_ID   strata1 strata2\n   <num>    <char>   <num>\n1:   123 WSM.5.4_1       1\n2:   122 WSM.5.4_1       1\n3:   119 WSM.5.3_1       1\n4:   126 WSM.6.1_1       1\n5:   128 WSM.6.2_1       1\n6:   112 WSM.5.2_1       1\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(EZ_strata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   EZ_ID   strata1 strata2\n   <num>    <char>   <num>\n1:    73 WSM.3.7_1       1\n2:    40 WSM.3.2_1       2\n3:    71 WSM.3.7_1       1\n4:    41 WSM.3.2_1       2\n5:    37 WSM.3.2_1       1\n6:    38 WSM.3.2_1       1\n```\n\n\n:::\n:::\n\n\nGreat - looks good. Now we can merge it with our EZ table that we read in from the .csv file produced by `gridEZ`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# merge\nEZ_tab <- merge(EZ_tab,EZ_strata,by=\"EZ_ID\")\n# check number of rows/EZs\nnrow(EZ_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 336\n```\n\n\n:::\n\n```{.r .cell-code}\n# look at the top of the table\nhead(EZ_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  EZ_ID      pop    N   strata1 strata2\n1     1 1465.795  444 WSM.1.1_1       1\n2     2 1488.862  307 WSM.1.1_1       1\n3     3 1048.678  132 WSM.1.1_1       1\n4     4 1006.009  301 WSM.1.1_1       2\n5     5  954.669  915 WSM.1.1_1       2\n6     6 1135.277 1509 WSM.1.1_1       3\n```\n\n\n:::\n:::\n\n\nExcellent - now we have a table with the following characteristic for each EZ in our sampling frame:\n\n-   ID\n\n-   population count\n\n-   grid cell count\n\n-   ID of strata 1 (administrative unit)\n\n-   ID of strata 2 (distance to coast category)\n\nWe can summarise the count of EZs per strata using the following code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(EZ_tab$strata1,EZ_tab$strata2)\n```\n:::\n\n\nOr we can plot the counts to visualise these results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(EZ_tab, aes(x = strata1, fill = as.factor(strata2))) +\n  geom_bar(position = \"stack\") +\n  labs(\n    title = \"Count of EZs per stratum\",\n    x = \"Admin. unit\",\n    y = \"Count\",\n    fill = \"Distance to coast\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)\n  ) +\n  scale_fill_discrete(labels = c(\"1\" = \"0-2km\", \"2\" = \"2-5km\", \"3\" = \">5km\"))\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial3_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n## Summary\n\nThis tutorial has covered:\n\n-   preparing datasets suitable for producing a sampling frame stratified by administrative units and distance to coast\n\n-   generating gridded sampling frames using the `gridEZ` function\n\n-   mapping the output sampling frame\n\n-   creating a table suitable for survey sample selection, i.e. containing EZ ID, population count and strata IDs\n\n## Feedback\n\nWe are very interested to know:\n\n-   how survey practitioners, researchers and data collectors are using gridEZ\n\n-   how these tutorials can be updated or improved\n\nPlease use the link below to provide any comments or feedback.\n\n<a id=\"feedback-link\" class=\"btn btn-dark\" target=\"_blank\">Give feedback</a>\n\n```{=html}\n<script>\ndocument.addEventListener(\"DOMContentLoaded\", function() {\n  // Your Google Form URL\n  const base = \"https://docs.google.com/forms/d/e/1FAIpQLSdOokaez2GCTBqDzOOJbqTxU2ydZU5TvzW7oO75BhVMnPo8Iw/viewform?usp=pp_url&entry.1982908603=\";\n\n  // Make sure the element exists\n  const link = document.getElementById(\"feedback-link\");\n  if (link) {\n    // Set the href dynamically\n    link.setAttribute(\"href\", base + encodeURIComponent(window.location.href));\n  }\n});\n</script>\n```\n",
    "supporting": [
      "gridEZ_tutorial3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}