<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Claire Dooley">

<title>Tutorial 1: detailed gridEZ example – Tutorials for Generating Gridded Sampling Frames</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./gridEZ_tutorial2.html" rel="next">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1bea93ccc161f891f1f595952294239b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QFGDL91VLC"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-QFGDL91VLC');
</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./gridEZ_tutorial1.html">Tutorial 1: detailed gridEZ example</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Tutorials for Generating Gridded Sampling Frames</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gridEZ_tutorial1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tutorial 1: detailed gridEZ example</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gridEZ_tutorial2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 2: applying gridEZ to different population datasets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gridEZ_tutorial3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 3: alternative sampling frame stratification example</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tutorial-aim" id="toc-tutorial-aim" class="nav-link active" data-scroll-target="#tutorial-aim">Tutorial Aim</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  <li><a href="#datasets" id="toc-datasets" class="nav-link" data-scroll-target="#datasets">Datasets</a>
  <ul>
  <li><a href="#population-counts-data" id="toc-population-counts-data" class="nav-link" data-scroll-target="#population-counts-data">Population counts data</a></li>
  <li><a href="#settlement-classification-data" id="toc-settlement-classification-data" class="nav-link" data-scroll-target="#settlement-classification-data">Settlement classification data</a></li>
  <li><a href="#administrative-unit-boundaries" id="toc-administrative-unit-boundaries" class="nav-link" data-scroll-target="#administrative-unit-boundaries">Administrative Unit Boundaries</a></li>
  </ul></li>
  <li><a href="#data-processing" id="toc-data-processing" class="nav-link" data-scroll-target="#data-processing">Data Processing</a></li>
  <li><a href="#gridez-sampling-frame-generation" id="toc-gridez-sampling-frame-generation" class="nav-link" data-scroll-target="#gridez-sampling-frame-generation">gridEZ: sampling frame generation</a></li>
  <li><a href="#evaluating-gridded-sampling-frames" id="toc-evaluating-gridded-sampling-frames" class="nav-link" data-scroll-target="#evaluating-gridded-sampling-frames">Evaluating Gridded Sampling Frames</a></li>
  <li><a href="#creation-of-table-for-survey-sample-selection" id="toc-creation-of-table-for-survey-sample-selection" class="nav-link" data-scroll-target="#creation-of-table-for-survey-sample-selection">Creation of table for survey sample selection</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#feedback" id="toc-feedback" class="nav-link" data-scroll-target="#feedback">Feedback</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tutorial 1: detailed gridEZ example</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Claire Dooley <a href="mailto:c.dooley@ucl.ac.uk" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Centre for Advanced Spatial Analysis, University College London
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<p><strong>Suggested citation:</strong> Dooley, C.A. (2025). gridEZ Tutorial 1 version 1.0</p>
<section id="tutorial-aim" class="level2">
<h2 class="anchored" data-anchor-id="tutorial-aim">Tutorial Aim</h2>
<p>The aim of this tutorial is to generate and evaluate a bespoke gridded sampling frame for Samoa based on gridded population data, gridded settlement data and administrative unit boundaries. The gridded sampling frame will contain gridded Enumeration Zones (EZs) that can be used for sampling survey units.</p>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<p>Throughout this tutorial we use several different R packages. The following code loads all the packages you will need. If you have not yet installed the <code>gridEZ2</code> package, please follow the instructions on the Tutorial Overview page.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># list of required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>required_packages <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"sf"</span>, <span class="st">"terra"</span>, <span class="st">"parallel"</span>, <span class="st">"data.table"</span>, <span class="st">"ggplot2"</span>, <span class="st">"scico"</span>, <span class="st">"patchwork"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># install missing packages</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">setdiff</span>(required_packages, <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>]))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parallel)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scico)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridEZ2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="datasets" class="level2">
<h2 class="anchored" data-anchor-id="datasets">Datasets</h2>
<p>Before we start with the datasets, create a folder for them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check your working directory</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># you may need to change your working directory to point to the location where the data_wsm folder sits. Use setwd() to change your working directory if needed</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># check whether the data folder already exists - if not, create the folder </span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">getwd</span>(),<span class="st">"/data_wsm/"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">dir.exists</span>(<span class="fu">paste0</span>(file_path))) {</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(file_path)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="population-counts-data" class="level3">
<h3 class="anchored" data-anchor-id="population-counts-data">Population counts data</h3>
<p>For tutorial 1, we will use WorldPop’s population counts data <span class="citation" data-cites="bondarenko2025">(<a href="#ref-bondarenko2025" role="doc-biblioref">Bondarenko M. 2025</a>)</span>. This global dataset has spatial resolution of 3 arc (approximately 100m at the equator) and has population constrained to grid cells that contain settlement. We will use the data for Samoa with estimated population counts for 2025 (alpha version: R2025A version v1).</p>
<p>More information about the dataset can be found here: <a href="https://hub.worldpop.org/geodata/summary?id=76095" class="uri">https://hub.worldpop.org/geodata/summary?id=76095</a></p>
<p>You can read in the data directly from the WorldPop server or you can download the data via the link above and then read the data into R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Option 1: read in directly from WP server</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>population_raster <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="st">"https://data.worldpop.org/GIS/Population/Global_2015_2030/R2025A/2025/WSM/v1/100m/constrained/wsm_pop_2025_CN_100m_R2025A_v1.tif"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Option 2: read in from file after download</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>population_raster <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">paste0</span>(<span class="fu">getwd</span>(),<span class="st">"/data_wsm/wsm_pop_2025_CN_100m_R2025A_v1.tif"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(population_raster,<span class="at">main=</span><span class="st">"Population distribution of Samoa (WorldPop data)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="settlement-classification-data" class="level3">
<h3 class="anchored" data-anchor-id="settlement-classification-data">Settlement classification data</h3>
<p>We will use Global Human Settlement Layer Settlement Model data (GHS-SMOD) <span class="citation" data-cites="pesaresi2024 schiavina2023">(<a href="#ref-pesaresi2024" role="doc-biblioref">Pesaresi et al. 2024</a>; <a href="#ref-schiavina2023" role="doc-biblioref">Schiavina, Melchiorri, and Pesaresi 2023</a>)</span>. To download the data, go to the GHS-SMOD website: <a href="https://human-settlement.emergency.copernicus.eu/download.php?ds=smod" class="uri">https://human-settlement.emergency.copernicus.eu/download.php?ds=smod</a></p>
<p>First, select the following options on the left hand side:</p>
<ul>
<li><p>Epoch = 2025</p></li>
<li><p>Resolution = 1km</p></li>
<li><p>Coord. system = Mollweide</p></li>
</ul>
<p>Second, hover your cursor over the map until you find Tile ID: R11_C2 (the Tile ID is written under the map). Click the tile to download. Unzip the data and add to the data folder called “data_wsm”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>settlement_raster <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">paste0</span>(<span class="fu">getwd</span>(),<span class="st">"/data_wsm/GHS_SMOD_E2025_GLOBE_R2023A_54009_1000_V2_0_R11_C2/GHS_SMOD_E2025_GLOBE_R2023A_54009_1000_V2_0_R11_C2.tif"</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(settlement_raster,<span class="at">main=</span><span class="st">"Settlement categories (GHS-SMOD data)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As you can see the GHS-SMOD tile covers a large area. We will crop this data shortly!</p>
</section>
<section id="administrative-unit-boundaries" class="level3">
<h3 class="anchored" data-anchor-id="administrative-unit-boundaries">Administrative Unit Boundaries</h3>
<p>For the administrative boundaries, we’ll use GADM as it has global coverage and has fully harmonized boundaries <span class="citation" data-cites="GADM2022">(<a href="#ref-GADM2022" role="doc-biblioref">GADM 2022</a>)</span>. Download GADM boundaries here by selecting Samoa from the drop down and then clicking “Shapefile”: <a href="https://gadm.org/download_country.html" class="uri">https://gadm.org/download_country.html</a></p>
<p>We use version 4.1 of the GADM data. If you prefer to use a different version, you can simply edit the file name in the <code>sf::st_read</code> code below. Unzip and add the shapefile to your data_wsm folder.</p>
<p>Read in level 2 administrative units.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>admin_sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="fu">paste0</span>(<span class="fu">getwd</span>(),<span class="st">"/data_WSM/gadm41_WSM_shp/gadm41_WSM_2.shp"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gadm41_WSM_2' from data source 
  `/Users/clairedooley/Documents/Research/gridEZ/gridEZ_tutorials/data_wsm/gadm41_WSM_shp/gadm41_WSM_2.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 43 features and 13 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -172.8041 ymin: -14.07722 xmax: -171.3977 ymax: -13.43981
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the list of fields in admin_sf</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(admin_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "GID_2"     "GID_0"     "COUNTRY"   "GID_1"     "NAME_1"    "NL_NAME_1"
 [7] "NAME_2"    "VARNAME_2" "NL_NAME_2" "TYPE_2"    "ENGTYPE_2" "CC_2"     
[13] "HASC_2"    "geometry" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the "GID_2" field which contains the level 2 unit IDs</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(admin_sf[<span class="st">"GID_2"</span>],<span class="at">main=</span><span class="st">"Level 2 administrative units for Samoa (GADM data)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="data-processing" class="level2">
<h2 class="anchored" data-anchor-id="data-processing">Data Processing</h2>
<p>The first processing step is to ensure all data have the same coordinate reference system (CRS).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># identify the CRS of the population raster</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>r_crs <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">crs</span>(population_raster)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># if the strata layers have a different CRS, transform</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(r_crs <span class="sc">!=</span>sf<span class="sc">::</span><span class="fu">st_crs</span>(admin_sf)){admin_sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_transform</span>(admin_sf, r_crs)}</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(r_crs <span class="sc">!=</span>terra<span class="sc">::</span><span class="fu">crs</span>(settlement_raster)){settlement_raster <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">project</span>(settlement_raster,terra<span class="sc">::</span><span class="fu">crs</span>(population_raster),<span class="at">method=</span><span class="st">"near"</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we need to convert the sf object containing administrative units into a raster. We do this using the grid of the population raster.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rasterize admin_sf</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>admin_raster <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rasterize</span>(admin_sf,population_raster,<span class="at">field=</span><span class="st">"GID_2"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># remove admin_sf object as we no long need it</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(admin_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The population data we are using has been constrained to settled areas. This means that grid cells that are settled have a population count and those that are not settled have an NA value. A sampling frame could be created for either settled areas only or for all areas within the focal region or country. There are pros and cons for each approach. We discuss and compare outputs for sampling frames constrained versus unconstrained to settled areas in a later tutorial. For now, we will create sampling frames that cover the whole of Samoa. As <code>gridEZ</code> recognizes any numerical value as a valid population count to be included in the sampling frame, we replace the NA grid cells, that are within the national boundary, with zero counts. We do this to distinguish grid cells inside the focal region/country from those outside the focal region/country. In this case, the outside of our focal country, Samoa, is sea and we certainly don’t want EZs there!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># replace grid cells of NA population counts that also have non-NA administrative unit values with 0 counts</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>population_raster[<span class="fu">is.na</span>(population_raster)<span class="sc">&amp;!</span><span class="fu">is.na</span>(admin_raster)] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we crop the settlement raster to the extent of the administrative units and population rasters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># crop </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>settlement_raster <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">crop</span>(settlement_raster,admin_raster,<span class="at">snap=</span><span class="st">"out"</span>,<span class="at">extend=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Excellent - now we have three rasters with the same CRS and extents. Let’s re-plot the cropped settlement raster.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(settlement_raster, <span class="at">main =</span> <span class="st">"Settlement categories (GHS-SMOD data)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>GHS classify areas into categories as shown in <a href="#tbl-table1.1" class="quarto-xref">Table&nbsp;1</a>. If you’d like to learn more about the classification process, please see section 2.6.2 of this report: <a href="https://human-settlement.emergency.copernicus.eu/documents/GHSL_Data_Package_2023.pdf?t=1727170839" class="uri">https://human-settlement.emergency.copernicus.eu/documents/GHSL_Data_Package_2023.pdf?t=1727170839</a></p>
<div class="cell">
<div id="tbl-table1.1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-table1.1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: GHS-SMOD Settlement categories
</figcaption>
<div aria-describedby="tbl-table1.1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Category</th>
<th style="text-align: left;">Merged categories</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: left;">Water</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">11</td>
<td style="text-align: left;">Mostly inhabited</td>
<td style="text-align: left;">Rural</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: left;">Dispersed rural</td>
<td style="text-align: left;">Rural</td>
</tr>
<tr class="even">
<td style="text-align: right;">13</td>
<td style="text-align: left;">Village</td>
<td style="text-align: left;">Rural</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: left;">Suburban or peri-urban</td>
<td style="text-align: left;">Urban</td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td style="text-align: left;">Semi-dense town</td>
<td style="text-align: left;">Urban</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: left;">Dense town</td>
<td style="text-align: left;">Urban</td>
</tr>
<tr class="even">
<td style="text-align: right;">30</td>
<td style="text-align: left;">City</td>
<td style="text-align: left;">Urban</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Looking at the settlement map above, we can see there are many instances where small areas of one category are completely surrounded by areas of other categories. Because we use the spatial distribution of these categories to stratify our sampling frame, EZs will never consist of grids cells from more than one category. This means that small areas of one category may have a total population size below the target population per EZ and, because an EZ can not cross strata, will become a single EZ with an undesirably low population size. To remedy this problem, we merge categories to reduce the number of instances this can occur. <a href="#tbl-table1.1" class="quarto-xref">Table&nbsp;1</a> shows how we will merge categories and here is the code to create to update the settlement raster to reflect these merged categories.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># re-define categories</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>settlement_raster[settlement_raster <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">30</span>,<span class="dv">23</span>,<span class="dv">22</span>,<span class="dv">21</span>)] <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="co"># urban</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>settlement_raster[settlement_raster <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">13</span>,<span class="dv">12</span>,<span class="dv">11</span>)] <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="co"># rural</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>settlement_raster[settlement_raster <span class="sc">==</span> <span class="dv">10</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span> <span class="co">#water</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># re-plot</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(settlement_raster, <span class="at">main =</span> <span class="st">"Merged settlement categories (GHS-SMOD data)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows our new settlement categories with urban and rural areas categorized as 1 and 2, respectively.</p>
<p>The final processing step is to increase the spatial resolution of the settlement raster to match the population and administrative unit rasters. We do this using the <code>terra::resample</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>settlement_raster <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">resample</span>(settlement_raster, population_raster, <span class="at">method =</span> <span class="st">"near"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Save the three rasters into a folder called “made” inside your “data_wsm” folder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check whether the data folder already exists - if not, create the folder </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">getwd</span>(),<span class="st">"/data_wsm/made/"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">dir.exists</span>(<span class="fu">paste0</span>(file_path))) {</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(file_path)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># save rasters</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">writeRaster</span>(admin_raster,<span class="fu">paste0</span>(file_path,<span class="st">"adminGADM.tif"</span>))</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">writeRaster</span>(population_raster,<span class="fu">paste0</span>(file_path,<span class="st">"popWP.tif"</span>))</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">writeRaster</span>(settlement_raster,<span class="fu">paste0</span>(file_path,<span class="st">"settGHS.tif"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="gridez-sampling-frame-generation" class="level2">
<h2 class="anchored" data-anchor-id="gridez-sampling-frame-generation">gridEZ: sampling frame generation</h2>
<p>The <code>gridEZ</code> function has been designed so that you can either apply pre-defined specifications or specify your own. More information on this can be found in the Tutorial Overview. Below we demonstrate both approaches.</p>
<p>If a sampling frame is being generated for a large geographic area the code will require a significant amount of computer memory. It is therefore good practice to remove R objects not being used and carry out a “garbage collection” before we start.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove all objects</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>()</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># garbage collection</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">gc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          used (Mb) gc trigger  (Mb) limit (Mb) max used  (Mb)
Ncells 1682003 89.9    3058031 163.4         NA  3058031 163.4
Vcells 2494422 19.1   10146329  77.5      36864  8669200  66.2</code></pre>
</div>
</div>
<p><code>gridEZ</code> utilises parallel processing to generate EZs for different strata at the same time. The number of parallel jobs that can be executed will depend on your computing system. You can work this out using the following code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># total number of cores available on your computer</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>parallel<span class="sc">::</span><span class="fu">detectCores</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we advise that you use your total number of cores minus 1 but you could use fewer (unless you only acces to one core, then you should specify 1 processing core) </span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>processing_cores <span class="ot">&lt;-</span> <span class="fu">max</span>(parallel<span class="sc">::</span><span class="fu">detectCores</span>() <span class="sc">-</span> <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>processing_cores</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13</code></pre>
</div>
</div>
<p>The <code>gridEZ</code> function reads input rasters straight from file so there is no need to read them into R before executing the function. Instead we define where you would like input rasters to be read in from and also where you would like outputs to be saved. These file pathways can be specified directly in the <code>gridEZ</code> function, however, I find it cleaner and easier to define these file pathways as objects with much shorter names.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># input</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>file_path_inputs <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">getwd</span>(),<span class="st">"/data_wsm/made/"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># output</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># check whether the output folders already exists - if not, create them</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>file_path_outputs_tuts <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">getwd</span>(),<span class="st">"/results_wsm/"</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">dir.exists</span>(<span class="fu">paste0</span>(file_path_outputs_tuts))) {</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(file_path_outputs_tuts)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>file_path_outputs <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">getwd</span>(),<span class="st">"/results_wsm/tutorial1/"</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">dir.exists</span>(<span class="fu">paste0</span>(file_path_outputs))) {</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(file_path_outputs)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can create our sampling frame. We’ll use the “large” EZ specifications so our sampling frame will be made up of EZs with population sizes mostly between 800 and 1,600.</p>
<p>We’ll generate the same sampling frame with two different approaches to demonstrate the different ways <code>gridEZ</code> can be applied: first using the predefined specifications, and then using user-defined specifications.</p>
<p>Note, the <code>run_ID</code> parameter is used to name output files and should be different for each new run of the gridEZ function.</p>
<p>Ok - let’s run <code>gridEZ</code> with pre-defined specifications. To do this we set <code>predefined_EZ_size</code> as TRUE and <code>EZ_target_size</code> as “large”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gridEZ function to generate sampling frame with large EZs: pre-defined specs</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>gridEZ2<span class="sc">::</span><span class="fu">gridEZ</span>(<span class="at">population_raster_path =</span> <span class="fu">paste0</span>(file_path_inputs,<span class="st">"popWP.tif"</span>), </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">strata1_raster_path =</span> <span class="fu">paste0</span>(file_path_inputs,<span class="st">"adminGADM.tif"</span>), </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">strata2_raster_path =</span> <span class="fu">paste0</span>(file_path_inputs,<span class="st">"settGHS.tif"</span>),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">predefined_EZ_size =</span> <span class="cn">TRUE</span>, </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">EZ_target_size =</span> <span class="st">"large"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">output_path =</span> <span class="fu">paste0</span>(file_path_outputs), </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">run_ID =</span> <span class="st">"wsm_large"</span>,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">ncores=</span>processing_cores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this example we are creating a sampling frame made up of “large” EZs but you can also produce sampling frames with “medium” or “small” EZs using the pre-defined <code>gridEZ</code> specifications. To do this you would replace “large” in the code above with “medium” or “small”.</p>
<p>Now let’s run <code>gridEZ</code> with user-defined specifications. We do this by setting <code>predefined_EZ_size</code> to be FALSE and specifying the parameters <code>target_pop_per_EZ</code> and <code>max_cells_per_EZ</code>.</p>
<p>Note, that the default for <code>predefined_EZ_size</code> is TRUE so if it is not included by the user, <code>gridEZ</code> will ignore <code>target_pop_per_EZ</code> and <code>max_cells_per_EZ</code> and the outputs will have (default) medium sized EZs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gridEZ function to generate sampling frame with large EZs: user-defined specs</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>gridEZ2<span class="sc">::</span><span class="fu">gridEZ</span>(<span class="at">population_raster_path =</span> <span class="fu">paste0</span>(file_path_inputs,<span class="st">"popWP.tif"</span>), </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">strata1_raster_path =</span> <span class="fu">paste0</span>(file_path_inputs,<span class="st">"adminGADM.tif"</span>), </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">strata2_raster_path =</span> <span class="fu">paste0</span>(file_path_inputs,<span class="st">"settGHS.tif"</span>),</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">predefined_EZ_size =</span> <span class="cn">FALSE</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">target_pop_per_EZ =</span> <span class="dv">1200</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">max_cells_per_EZ =</span> <span class="dv">2500</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">output_path =</span> <span class="fu">paste0</span>(file_path_outputs), </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">run_ID =</span> <span class="st">"wsm_large_ownspecs"</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">ncores=</span>processing_cores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you can see from the code above, the user-defined specifications route offers flexibility as <code>target_pop_per_EZ</code> and <code>max_cells_per_EZ</code> can be tailored to specific survey needs.</p>
<p>Great - now we can look at the results!</p>
</section>
<section id="evaluating-gridded-sampling-frames" class="level2">
<h2 class="anchored" data-anchor-id="evaluating-gridded-sampling-frames">Evaluating Gridded Sampling Frames</h2>
<p>The <code>gridEZ</code> function produces two output files:</p>
<ul>
<li><p>.csv with file name beginning “EZ_Pop_Ncells_”. Tabular results for EZs within the sampling frame.</p></li>
<li><p>.tif (raster) with file name beginning “EZ_IDs_”. Raster of the sampling frame.</p></li>
</ul>
<p>Let’s start by looking at the outputs for the sampling frame generated using the pre-defined settings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in EZs table of your sampling frame </span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>EZ_tab <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">paste0</span>(file_path_outputs, <span class="st">"EZ_Pop_Ncells_wsm_large.csv"</span>),<span class="at">header=</span>T)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># number of EZs in your sampling frame</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(EZ_tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 305</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the first rows</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(EZ_tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  EZ_ID       pop    N
1     1  947.8968  200
2     2 1257.4823  200
3     3 1163.7940  217
4     4  908.7108  492
5     5  967.2034 1508
6     6  923.8834  668</code></pre>
</div>
</div>
<p>Each row of the table gives the results for each EZ. There are 305 rows, i.e.&nbsp;305 EZs in the sampling frame. From the top row, we know that the focal EZ has an ID of 1, a population size of 948, and contains 200 grid cells.</p>
<p>To check that the sampling frame generated using the user-defined settings is the same, we can compare EZ tables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in EZs table of your sampling frame </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>EZ_tab_ownspecs <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">paste0</span>(file_path_outputs, <span class="st">"EZ_Pop_Ncells_wsm_large_ownspecs.csv"</span>),<span class="at">header=</span>T)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># number of EZs in your sampling frame</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(EZ_tab_ownspecs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 305</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the first rows</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(EZ_tab_ownspecs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  EZ_ID       pop    N
1     1  947.8968  200
2     2 1257.4823  200
3     3 1163.7940  217
4     4  908.7108  492
5     5  967.2034 1508
6     6  923.8834  668</code></pre>
</div>
</div>
<p>From this we can see that the same sampling frame has been made. The goal of creating the two sampling frames was to demonstrate the two different approached. Now you have everything you need to start creating sampling frames using a variety of target EZ sizes.</p>
<p>Let’s carry on evaluating our sampling frame (we could use either pre- or user-defined outputs here). First, we’ll create a map of the EZs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in your sampling frame raster &amp; plot</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>EZ <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">paste0</span>(file_path_outputs,<span class="st">"EZ_IDs_wsm_large.tif"</span>))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># simple plot</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co"># convert to sf polygons</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>res_poly <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">as.polygons</span>(EZ, <span class="at">dissolve =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>res_poly <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_as_sf</span>(res_poly)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co"># merge the ppolygons and EZ IDs</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>res_poly <span class="ot">&lt;-</span> <span class="fu">merge</span>(res_poly,EZ_tab,<span class="at">by=</span><span class="st">"EZ_ID"</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="co"># plot EZ polygons coloured by EZ IDs</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res_poly[,<span class="st">"geometry"</span>],<span class="at">main=</span><span class="st">"Spatial distribution of EZs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot above shows the EZ boundaries. Now let’s look at the population sizes of the EZs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot EZ polygons coloured by population per EZ</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res_poly[,<span class="st">"pop"</span>],<span class="at">main=</span><span class="st">"EZ population size"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>EZs with relatively low population size are located in the centre of the islands where the population is sparse. But if we had a target population per EZ, shouldn’t all the EZs be within the desirable range of 800-1600 for the “large” EZ setting? No - because we also have a maximum geographic size per EZ too! Let’s map the number of grid cells per EZ.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot EZ polygons coloured by number of grid cells per EZ</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res_poly[,<span class="st">"N"</span>],<span class="at">main=</span><span class="st">"EZ grid cells count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The maximum geographic size per EZ for the large EZ setting is 2,500 grid cells. However, <code>gridEZ</code> allows blocks up to 1.5 times the value given for the maximum geographic size to be accepted as an EZ. So in our example this is 3,750. The <code>gridEZ</code> function allows this leeway above the ideal maximum geographic size per EZ because the requirement to create compact shapes restricts how the algorithm can combine/split blocks of grid cells. Without this extra flexibility, we’d end up with many EZs much smaller than the maximum geographic size that also have low population counts - two undesirable traits. It is better for an EZ to be slightly larger in geographic size if that helps keep its population closer to the target.</p>
<p>If a survey design requires a very strict maximum geographic size of survey units, the <code>max_cells_per_EZ</code> parameter can be adjusted accordingly, e.g.&nbsp;if the hard limit is 1,500 grid cells, the user could set <code>max_cells_per_EZ</code> to be 1,000. In this case, most sparsely populated EZs would have sizes close to 1,000 cells and only some would have sizes close to 1,500.</p>
<p>Now that we’ve looked at the spatial distribution of population and grid cells per EZ, let’s create a scatter plot to look at the two EZ characteristics together.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(res_poly, <span class="fu">aes</span>(<span class="at">x =</span> N, <span class="at">y =</span> pop)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># grey scatter plot area for values within acceptable values</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">xmin =</span> <span class="dv">0</span>, <span class="at">xmax =</span> <span class="dv">3750</span>,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">ymin =</span> <span class="dv">800</span>, <span class="at">ymax =</span> <span class="dv">1600</span>,</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">"grey30"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>,</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">xmin =</span> <span class="dv">1875</span>, <span class="at">xmax =</span> <span class="dv">3750</span>,</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> <span class="dv">800</span>,</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">"grey30"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># include threshold lines</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="dv">800</span>, <span class="dv">1600</span>),</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="dv">1875</span>, <span class="dv">3750</span>),</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"blue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"grid cells per EZ"</span>,</span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"pop count per EZ"</span>,</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">""</span></span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The red horizontal lines indicate the desirable range for population per EZ and the blue vertical lines show the acceptable geographic size range for EZs with undesirably low population. You can see that no EZs are geographically larger than the acceptable maximum grid cells per EZ of 3,750. Therefore, all the EZs that fall between the red horizontal lines meet our criteria for ideal EZs (n = 169). The EZs that fall between the blue vertical lines but below the lower red horizontal line have a desirable geographic size given that they are located in sparsely populated areas. These are acceptable EZs (n=83). Generally, all EZs sitting outside of these areas on the scatter plot, (i.e.&nbsp;outside of the grey areas), are not considered to be acceptable EZs given our criteria.</p>
<p>However, there are a number of restrictions that may lead to the criteria not being met. One example is when a single grid cell has population size greater than the upper end of the desirable population range, e.g.&nbsp;in densely populated areas of cities. The grid based nature of our algorithm means that we can not split individual grid cells and so these become individual EZs. On the scatter plot these EZs would be plotted on the far left (1 grid cell per EZ) above the upper red horizontal line. We can see from our scatter plot that, in this example, there are no single cell EZs with population size greater than 1,600 so no EZs fall into this category.</p>
<p>For our sampling frame, let’s investigate all the EZs outside of the grey areas on our scatter plot. To help with this, we can categorize the EZs by where they sit on the scatter plot using the following code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>res_poly<span class="sc">$</span>cat <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># category 1: meets pop and geog criteria </span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>res_poly<span class="sc">$</span>cat[res_poly<span class="sc">$</span>N<span class="sc">&lt;=</span><span class="dv">3750</span> <span class="sc">&amp;</span> res_poly<span class="sc">$</span>pop<span class="sc">&gt;=</span><span class="dv">800</span> <span class="sc">&amp;</span> res_poly<span class="sc">$</span>pop<span class="sc">&lt;=</span><span class="dv">1600</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># category 2: low pop but meets max geog range</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>res_poly<span class="sc">$</span>cat[res_poly<span class="sc">$</span>N<span class="sc">&gt;=</span><span class="dv">1875</span> <span class="sc">&amp;</span> res_poly<span class="sc">$</span>N<span class="sc">&lt;=</span><span class="dv">3750</span> <span class="sc">&amp;</span> res_poly<span class="sc">$</span>pop<span class="sc">&lt;</span><span class="dv">800</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="co"># category 3: high pop but only 1 cell</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>res_poly<span class="sc">$</span>cat[res_poly<span class="sc">$</span>N<span class="sc">==</span><span class="dv">1</span> <span class="sc">&amp;</span> res_poly<span class="sc">$</span>pop<span class="sc">&gt;</span><span class="dv">1600</span>] <span class="ot">&lt;-</span><span class="dv">3</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="co"># category 4: below max geog range but over pop max and has more than 1 cell</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>res_poly<span class="sc">$</span>cat[res_poly<span class="sc">$</span>N<span class="sc">&gt;</span><span class="dv">1</span> <span class="sc">&amp;</span> res_poly<span class="sc">$</span>pop<span class="sc">&gt;</span><span class="dv">1600</span>] <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="co"># category 5: pop &amp; cell count are too low</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>res_poly<span class="sc">$</span>cat[res_poly<span class="sc">$</span>N<span class="sc">&lt;</span><span class="dv">1875</span> <span class="sc">&amp;</span> res_poly<span class="sc">$</span>pop<span class="sc">&lt;</span><span class="dv">800</span>] <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>res_poly<span class="sc">$</span>cat <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(res_poly<span class="sc">$</span>cat)</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="co"># re-do scatter plot colour coded by category</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="co"># define the colour coding first</span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>cat_cols <span class="ot">&lt;-</span> scales<span class="sc">::</span><span class="fu">hue_pal</span>()(<span class="dv">5</span>)</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(res_poly, <span class="fu">aes</span>(<span class="at">x =</span> N, <span class="at">y =</span> pop, <span class="at">colour =</span> cat)) <span class="sc">+</span></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> cat_cols) <span class="sc">+</span></span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"grid cells per EZ"</span>,</span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"pop count per EZ"</span>,</span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"Category"</span>,</span>
<span id="cb41-28"><a href="#cb41-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">""</span></span>
<span id="cb41-29"><a href="#cb41-29" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Cateogories 1 and 2 correspond to the EZs we described above. Category 3 corresponds to single celled EZs with high population counts - as mentioned, we don’t have any in this Samoa example. Category 4 consists of EZs whose population size is too big based on our criteria and category 5 consists of EZs whose population size is too small based on our criteria. Let’s count the EZs in each category:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(res_poly<span class="sc">$</span>cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   4   5 
169  83   5  48 </code></pre>
</div>
</div>
<p>There are 252 EZs that fall into categories 1 and 2 out of a total of 305 EZs in our sampling frame (i.e.&nbsp;83%. of all our EZs). There are 5 EZs in category 4 and 48 EZs in category 5. We can map the EZs by category to see where they are located.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res_poly[<span class="st">"cat"</span>], <span class="at">pal =</span> cat_cols, <span class="at">main=</span><span class="st">"EZs by evaluation category"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Straight away we can easily see a handful of EZs in category 5. Given their category, can you guess which points in the scatter plot correspond to these? Hint: their geographic size is only slightly below the target grid cells per EZ for sparsely populated areas. Of greater concern are the EZs that are very small in both population and geographic size. Let’s zoom in on an area to take a closer look.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># zoomed in map</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res_poly[<span class="st">"cat"</span>], <span class="at">pal =</span> cat_cols,<span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">13.96</span>,<span class="sc">-</span><span class="fl">13.77</span>),<span class="at">xlim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">172.27</span>,<span class="sc">-</span><span class="fl">171.95</span>), <span class="at">main=</span><span class="st">"EZs by evaluation category - zoomed in"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Samoa consists of two main island - Savai’i in the west and Upolu in the east - and many smaller islands. Here we see a tiny island situated between the two main islands that has a single EZ which is in category 5, i.e.&nbsp;population smaller than the target EZ population size. It is generally preferable to have EZs be contiguous in space so that survey field teams do not need to travel through non-survey unit areas to cover a whole unit. The <code>gridEZ</code> algorithm therefore enforces spatial contiguity for EZs. This results in small islands like this one being one single EZ - in most survey designs, this is preferable over several islands being part of the same EZ.</p>
<p>Now let’s focus on the section of Upolu that we see in the above map.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># zoom in more and use ggplot</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="co"># define the categories plot</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(res_poly) <span class="sc">+</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> cat), <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> cat_cols) <span class="sc">+</span>   <span class="co"># same palette as before</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">172.08</span>, <span class="sc">-</span><span class="fl">171.98</span>),</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">13.95</span>, <span class="sc">-</span><span class="fl">13.82</span>),</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="cn">FALSE</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Category"</span>,</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Longitude"</span>,</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Latitude"</span>,</span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">""</span></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a><span class="co"># read in the settlement raster and admin polygons</span></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a>settlement_raster <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">paste0</span>(file_path_inputs,<span class="st">"settGHS.tif"</span>))</span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>admin_sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="fu">paste0</span>(<span class="fu">getwd</span>(),<span class="st">"/data_WSM/gadm41_WSM_shp/gadm41_WSM_2.shp"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gadm41_WSM_2' from data source 
  `/Users/clairedooley/Documents/Research/gridEZ/gridEZ_tutorials/data_wsm/gadm41_WSM_shp/gadm41_WSM_2.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 43 features and 13 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -172.8041 ymin: -14.07722 xmax: -171.3977 ymax: -13.43981
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot these survey strata</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># convert the raster into a data.frame first</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>settlement_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(settlement_raster, <span class="at">xy =</span> <span class="cn">TRUE</span>, <span class="at">na.rm =</span> <span class="cn">FALSE</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>settlement_df<span class="sc">$</span>GHS_SMOD_E2025_GLOBE_R2023A_54009_1000_V2_0_R11_C2 <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(settlement_df<span class="sc">$</span>GHS_SMOD_E2025_GLOBE_R2023A_54009_1000_V2_0_R11_C2)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="co"># define strata plot</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="at">data =</span> settlement_df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> GHS_SMOD_E2025_GLOBE_R2023A_54009_1000_V2_0_R11_C2)) <span class="sc">+</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> admin_sf, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_scico_d</span>(<span class="at">palette =</span> <span class="st">"nuuk"</span>, <span class="at">na.value =</span> <span class="st">"transparent"</span>) <span class="sc">+</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">172.08</span>, <span class="sc">-</span><span class="fl">171.98</span>),</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">13.95</span>, <span class="sc">-</span><span class="fl">13.82</span>),</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="cn">FALSE</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Value"</span>,</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Longitude"</span>,</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Latitude"</span>,</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">""</span></span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the left hand plot we see several category 5 EZs. The right hand plot shows our two strata layers. The overall spatial stratification for the sampling frame is a combination of the two, i.e.&nbsp;stratum 1 = settlement type 1 in admin unit A; stratum 2 = settlement type 2 in admin unit A; stratum 3 = settlement type 1 in admin unit B; stratum 4 = settlement type 2 in admin unit B; etc. The overall spatial stratification delineates what we consider “uncrossable” boundaries and <code>gridEZ</code> therefore does not allow EZs to cross different strata. EZs are always contained within one stratum. This stratification approach is important for survey design but can lead to EZs with small population and small geograhpic size, depending on how the layers used to define the overall stratification intersect with one another. In our example, the overall stratification based on GHS-SMOD and GADM administrative units essentially consists of little psuedo islands within the landmass and explains most of the category 5 EZs that we see in the left hand plot above.</p>
<p>The <code>gridEZ</code> algorithm balances compactness of EZ shapes against meeting the population and geographic criteria. In several cases, this can lead to a decision not to add or split a block of grid cells and instead call it good as an EZ. This is the likely explanation for the remaining EZs in categories 4 and 5.</p>
</section>
<section id="creation-of-table-for-survey-sample-selection" class="level2">
<h2 class="anchored" data-anchor-id="creation-of-table-for-survey-sample-selection">Creation of table for survey sample selection</h2>
<p>Surveys require a table of survey sampling frame units (here, these are EZs) to sample from. We currently have a table of EZs and their population counts, but as many surveys will want to sample a specific number of units per stratum (stratified sampling) we need to add the corresponding stratum for each EZ.</p>
<p>We can do this by spatially linking the EZ IDs raster with the two strata rasters. The result is a table containing the information from the three rasters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in the strata raster</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>admin_raster <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">paste0</span>(file_path_inputs,<span class="st">"adminGADM.tif"</span>))</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>settlement_raster <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="fu">paste0</span>(file_path_inputs,<span class="st">"settGHS.tif"</span>))</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="co"># the extent of the EZ raster is defined by the presence of EZs and may be different to the extent of the input files which was set by the population raster</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="co"># remember EZs are created for grid cells with non-NA values across all 3 input rasters, not everywhere there is population</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># because of this we extend the EZ raster to match the input rasters</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>EZ <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">extend</span>(EZ,admin_raster)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="co"># create a table of EZ strata values</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="co"># we need to create a table with vectors of values in each raster</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="co"># as the admin_raster contains categories, we want the category labels rather than their corresponding numeric value</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>admin_cats <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">cats</span>(admin_raster)[[<span class="dv">1</span>]]</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>admin_labels <span class="ot">&lt;-</span> admin_cats[<span class="fu">match</span>(admin_raster[], admin_cats[,<span class="dv">1</span>]),<span class="dv">2</span>]</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a><span class="co"># as we defined the distance categories by numeric values, we can directly use those raster values</span></span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>EZ_strata <span class="ot">&lt;-</span> data.table<span class="sc">::</span><span class="fu">data.table</span>(EZ[],</span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a>                                    admin_labels,</span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a>                                    settlement_raster[])</span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a><span class="co"># set column names, change as needed</span></span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(EZ_strata) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"EZ_ID"</span>,<span class="st">"strata1"</span>,<span class="st">"strata2"</span>) </span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a><span class="co"># reduce table down to a single row per EZ</span></span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a>EZ_strata <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(EZ_strata)</span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a>EZ_strata <span class="ot">&lt;-</span> <span class="fu">unique</span>(EZ_strata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s have a look at the top of the table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the top of the table</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(EZ_strata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   EZ_ID   strata1 strata2
   &lt;num&gt;    &lt;char&gt;   &lt;num&gt;
1:    98 WSM.5.4_1       2
2:    96 WSM.5.3_1       2
3:   100 WSM.6.1_1       2
4:   105 WSM.6.2_1       2
5:   101 WSM.6.1_1       2
6:    99 WSM.5.4_1       2</code></pre>
</div>
</div>
<p>Great - looks good. Now we can merge it with our EZ table that we read in from the .csv file produced by <code>gridEZ</code> so that we have EZ population and strata information all in one table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># merge</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>EZ_tab <span class="ot">&lt;-</span> <span class="fu">merge</span>(EZ_tab,EZ_strata,<span class="at">by=</span><span class="st">"EZ_ID"</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="co"># check number of rows/EZs</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(EZ_tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 305</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the top of the table</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(EZ_tab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  EZ_ID       pop    N   strata1 strata2
1     1  947.8968  200 WSM.1.1_1       1
2     2 1257.4823  200 WSM.1.1_1       1
3     3 1163.7940  217 WSM.1.1_1       1
4     4  908.7108  492 WSM.1.1_1       2
5     5  967.2034 1508 WSM.1.1_1       2
6     6  923.8834  668 WSM.1.1_1       2</code></pre>
</div>
</div>
<p>Excellent - now we have a table with the following characteristic for each EZ in our sampling frame:</p>
<ul>
<li><p>ID</p></li>
<li><p>population count</p></li>
<li><p>grid cell count</p></li>
<li><p>ID of strata 1 (administrative unit)</p></li>
<li><p>ID of strata 2 (settlement category)</p></li>
</ul>
<p>Finally, it may be useful to count the EZs in each strata. We can summarise this in a table as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(EZ_tab<span class="sc">$</span>strata1,EZ_tab<span class="sc">$</span>strata2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For visual inspection we can also plot it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(EZ_tab, <span class="fu">aes</span>(<span class="at">x =</span> strata1, <span class="at">fill =</span> <span class="fu">as.factor</span>(strata2))) <span class="sc">+</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Count of EZs per stratum"</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Admin. unit"</span>,</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Settlement type"</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust =</span> <span class="dv">1</span>)</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"1"</span> <span class="ot">=</span> <span class="st">"urban"</span>, <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"rural"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gridEZ_tutorial1_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>This tutorial has covered:</p>
<ul>
<li><p>preparing example datasets suitable for the <code>gridEZ</code> R function</p></li>
<li><p>generating gridded sampling frames using two <code>gridEZ</code> options:</p>
<ol type="1">
<li><p>applying pre-defined specifications</p></li>
<li><p>applying user-defined specifications</p></li>
</ol></li>
<li><p>summarising output sampling frames</p></li>
<li><p>evaluating sampling frame EZs</p></li>
<li><p>creating a table suitable for survey sample selection, i.e.&nbsp;containing EZ ID, population count and strata IDs</p></li>
</ul>
</section>
<section id="feedback" class="level2">
<h2 class="anchored" data-anchor-id="feedback">Feedback</h2>
<p>We are very interested to know:</p>
<ul>
<li><p>how survey practitioners, researchers and data collectors are using gridEZ</p></li>
<li><p>how these tutorials can be updated or improved</p></li>
</ul>
<p>Please use the link below to provide any comments or feedback.</p>
<p><a id="feedback-link" class="btn btn-dark" target="_blank">Give feedback</a></p>
<script>
document.addEventListener("DOMContentLoaded", function() {
  // Your Google Form URL
  const base = "https://docs.google.com/forms/d/e/1FAIpQLSdOokaez2GCTBqDzOOJbqTxU2ydZU5TvzW7oO75BhVMnPo8Iw/viewform?usp=pp_url&entry.1982908603=";

  // Make sure the element exists
  const link = document.getElementById("feedback-link");
  if (link) {
    // Set the href dynamically
    link.setAttribute("href", base + encodeURIComponent(window.location.href));
  }
});
</script>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-bondarenko2025" class="csl-entry" role="listitem">
Bondarenko M., Tejedor-Garavito N., Priyatikanto R. 2025. <span>“Constrained Estimates of 2015-2030 Total Number of People Per Grid Square at a Resolution of 3 Arc (Approximately 100m at the Equator) R2025A Version V1.”</span> WorldPop - School of Geography; Environmental Science, University of Southampton. <a href="https://doi.org/10.5258/SOTON/WP00839">https://doi.org/10.5258/SOTON/WP00839</a>.
</div>
<div id="ref-GADM2022" class="csl-entry" role="listitem">
GADM. 2022. <span>“GADM Database of Global Administrative Areas, Version 4.1.”</span> <a href="https://gadm.org/download_country.html">https://gadm.org/download_country.html</a>.
</div>
<div id="ref-pesaresi2024" class="csl-entry" role="listitem">
Pesaresi, Martino, Marcello Schiavina, Panagiotis Politis, Sergio Freire, Katarzyna Krasnodębska, Johannes H. Uhl, Alessandra Carioli, et al. 2024. <span>“Advances on the Global Human Settlement Layer by Joint Assessment of Earth Observation and Population Survey Data.”</span> <em>International Journal of Digital Earth</em> 17 (1). <a href="https://doi.org/10.1080/17538947.2024.2390454">https://doi.org/10.1080/17538947.2024.2390454</a>.
</div>
<div id="ref-schiavina2023" class="csl-entry" role="listitem">
Schiavina, Marcello, Michele Melchiorri, and Martino Pesaresi. 2023. <span>“GHS-SMOD R2023A - GHS Settlement Layers, Application of the Degree of Urbanisation Methodology (Stage I) to GHS-POP R2023A and GHS-BUILT-S R2023A, Multitemporal (1975-2030).”</span> European Commission, Joint Research Centre (JRC). <a href="https://doi.org/10.2905/A0DF7A6F-49DE-46EA-9BDE-563437A6E2BA">https://doi.org/10.2905/A0DF7A6F-49DE-46EA-9BDE-563437A6E2BA</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
  </div>
  <div class="nav-page nav-page-next">
      <a href="./gridEZ_tutorial2.html" class="pagination-link" aria-label="Tutorial 2: applying gridEZ to different population datasets">
        <span class="nav-page-text">Tutorial 2: applying gridEZ to different population datasets</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>