{
  "hash": "34621722a8c628bfa589e92d93ed1ff3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tutorial 1: detailed gridEZ example\"\nauthor: \n  - name: \"Claire Dooley\"\n    affiliation: \"Centre for Advanced Spatial Analysis, University College London\"\n    email: \"c.dooley@ucl.ac.uk\"\nformat: html\neditor: visual\nsuggested-citation: \"Dooley, C.A. (2025). gridEZ Tutorial 1 version 1.0\"\nbibliography: references.bib\n---\n\n**Suggested citation:** {{< meta suggested-citation >}}\n\n## Tutorial Aim\n\nThe aim of this tutorial is to generate and evaluate a bespoke gridded sampling frame for Samoa based on gridded population data, gridded settlement data and administrative unit boundaries. The gridded sampling frame will contain gridded Enumeration Zones (EZs) that can be used for sampling survey units.\n\n## Packages\n\nThroughout this tutorial we use several different R packages. The following code loads all the packages you will need. If you have not yet installed the `gridEZ2` package, please follow the instructions on the Tutorial Overview page.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# list of required packages\nrequired_packages <- c(\"sf\", \"terra\", \"parallel\", \"data.table\", \"ggplot2\", \"scico\", \"patchwork\")\n\n# install missing packages\ninstall.packages(setdiff(required_packages, installed.packages()[, \"Package\"]))\n\n# load packages\nlibrary(sf)\nlibrary(terra)\nlibrary(data.table)\nlibrary(parallel)\nlibrary(ggplot2)\nlibrary(scico)\nlibrary(patchwork)\nlibrary(gridEZ2)\n```\n:::\n\n\n## Datasets\n\nBefore we start with the datasets, create a folder for them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check your working directory\ngetwd()\n\n# you may need to change your working directory to point to the location where the data_wsm folder sits. Use setwd() to change your working directory if needed\n\n# check whether the data folder already exists - if not, create the folder \nfile_path <- paste0(getwd(),\"/data_wsm/\")\nif (!dir.exists(paste0(file_path))) {\n  dir.create(file_path)\n}\n```\n:::\n\n\n### Population counts data\n\nFor tutorial 1, we will use WorldPop's population counts data [@bondarenko2025]. This global dataset has spatial resolution of 3 arc (approximately 100m at the equator) and has population constrained to grid cells that contain settlement. We will use the data for Samoa with estimated population counts for 2025 (alpha version: R2025A version v1).\n\nMore information about the dataset can be found here: <https://hub.worldpop.org/geodata/summary?id=76095>\n\nYou can read in the data directly from the WorldPop server or you can download the data via the link above and then read the data into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Option 1: read in directly from WP server\npopulation_raster <- terra::rast(\"https://data.worldpop.org/GIS/Population/Global_2015_2030/R2025A/2025/WSM/v1/100m/constrained/wsm_pop_2025_CN_100m_R2025A_v1.tif\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Option 2: read in from file after download\npopulation_raster <- terra::rast(paste0(getwd(),\"/data_wsm/wsm_pop_2025_CN_100m_R2025A_v1.tif\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(population_raster,main=\"Population distribution of Samoa (WorldPop data)\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### Settlement classification data\n\nWe will use Global Human Settlement Layer Settlement Model data (GHS-SMOD) [@pesaresi2024; @schiavina2023]. To download the data, go to the GHS-SMOD website: <https://human-settlement.emergency.copernicus.eu/download.php?ds=smod>\n\nFirst, select the following options on the left hand side:\n\n-   Epoch = 2025\n\n-   Resolution = 1km\n\n-   Coord. system = Mollweide\n\nSecond, hover your cursor over the map until you find Tile ID: R11_C2 (the Tile ID is written under the map). Click the tile to download. Unzip the data and add to the data folder called \"data_wsm\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsettlement_raster <- terra::rast(paste0(getwd(),\"/data_wsm/GHS_SMOD_E2025_GLOBE_R2023A_54009_1000_V2_0_R11_C2/GHS_SMOD_E2025_GLOBE_R2023A_54009_1000_V2_0_R11_C2.tif\"))\n\nplot(settlement_raster,main=\"Settlement categories (GHS-SMOD data)\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nAs you can see the GHS-SMOD tile covers a large area. We will crop this data shortly!\n\n### Administrative Unit Boundaries\n\nFor the administrative boundaries, we'll use GADM as it has global coverage and has fully harmonized boundaries [@GADM2022]. Download GADM boundaries here by selecting Samoa from the drop down and then clicking \"Shapefile\": <https://gadm.org/download_country.html>\n\nWe use version 4.1 of the GADM data. If you prefer to use a different version, you can simply edit the file name in the `sf::st_read` code below. Unzip and add the shapefile to your data_wsm folder.\n\nRead in level 2 administrative units.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadmin_sf <- sf::st_read(paste0(getwd(),\"/data_WSM/gadm41_WSM_shp/gadm41_WSM_2.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `gadm41_WSM_2' from data source \n  `/Users/clairedooley/Documents/Research/gridEZ/gridEZ_tutorials/data_wsm/gadm41_WSM_shp/gadm41_WSM_2.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 43 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -172.8041 ymin: -14.07722 xmax: -171.3977 ymax: -13.43981\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# look at the list of fields in admin_sf\nnames(admin_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"GID_2\"     \"GID_0\"     \"COUNTRY\"   \"GID_1\"     \"NAME_1\"    \"NL_NAME_1\"\n [7] \"NAME_2\"    \"VARNAME_2\" \"NL_NAME_2\" \"TYPE_2\"    \"ENGTYPE_2\" \"CC_2\"     \n[13] \"HASC_2\"    \"geometry\" \n```\n\n\n:::\n\n```{.r .cell-code}\n# plot the \"GID_2\" field which contains the level 2 unit IDs\nplot(admin_sf[\"GID_2\"],main=\"Level 2 administrative units for Samoa (GADM data)\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n## Data Processing\n\nThe first processing step is to ensure all data have the same coordinate reference system (CRS).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# identify the CRS of the population raster\nr_crs <- terra::crs(population_raster)\n\n# if the strata layers have a different CRS, transform\nif(r_crs !=sf::st_crs(admin_sf)){admin_sf <- sf::st_transform(admin_sf, r_crs)}\nif(r_crs !=terra::crs(settlement_raster)){settlement_raster <- terra::project(settlement_raster,terra::crs(population_raster),method=\"near\")}\n```\n:::\n\n\nNext, we need to convert the sf object containing administrative units into a raster. We do this using the grid of the population raster.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# rasterize admin_sf\nadmin_raster <- terra::rasterize(admin_sf,population_raster,field=\"GID_2\")\n\n# remove admin_sf object as we no long need it\nrm(admin_sf)\n```\n:::\n\n\nThe population data we are using has been constrained to settled areas. This means that grid cells that are settled have a population count and those that are not settled have an NA value. A sampling frame could be created for either settled areas only or for all areas within the focal region or country. There are pros and cons for each approach. We discuss and compare outputs for sampling frames constrained versus unconstrained to settled areas in a later tutorial. For now, we will create sampling frames that cover the whole of Samoa. As `gridEZ` recognizes any numerical value as a valid population count to be included in the sampling frame, we replace the NA grid cells, that are within the national boundary, with zero counts. We do this to distinguish grid cells inside the focal region/country from those outside the focal region/country. In this case, the outside of our focal country, Samoa, is sea and we certainly don't want EZs there!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# replace grid cells of NA population counts that also have non-NA administrative unit values with 0 counts\npopulation_raster[is.na(population_raster)&!is.na(admin_raster)] <- 0\n```\n:::\n\n\nNext, we crop the settlement raster to the extent of the administrative units and population rasters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# crop \nsettlement_raster <- terra::crop(settlement_raster,admin_raster,snap=\"out\",extend=TRUE)\n```\n:::\n\n\nExcellent - now we have three rasters with the same CRS and extents. Let's re-plot the cropped settlement raster.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(settlement_raster, main = \"Settlement categories (GHS-SMOD data)\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nGHS classify areas into categories as shown in @tbl-table1.1. If you'd like to learn more about the classification process, please see section 2.6.2 of this report: <https://human-settlement.emergency.copernicus.eu/documents/GHSL_Data_Package_2023.pdf?t=1727170839>\n\n\n::: {#tbl-table1.1 .cell tbl-cap='GHS-SMOD Settlement categories'}\n::: {.cell-output-display}\n\n\n| Code|Category               |Merged categories |\n|----:|:----------------------|:-----------------|\n|   10|Water                  |NA                |\n|   11|Mostly inhabited       |Rural             |\n|   12|Dispersed rural        |Rural             |\n|   13|Village                |Rural             |\n|   21|Suburban or peri-urban |Urban             |\n|   22|Semi-dense town        |Urban             |\n|   23|Dense town             |Urban             |\n|   30|City                   |Urban             |\n\n\n:::\n:::\n\n\nLooking at the settlement map above, we can see there are many instances where small areas of one category are completely surrounded by areas of other categories. Because we use the spatial distribution of these categories to stratify our sampling frame, EZs will never consist of grids cells from more than one category. This means that small areas of one category may have a total population size below the target population per EZ and, because an EZ can not cross strata, will become a single EZ with an undesirably low population size. To remedy this problem, we merge categories to reduce the number of instances this can occur. @tbl-table1.1 shows how we will merge categories and here is the code to create to update the settlement raster to reflect these merged categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# re-define categories\nsettlement_raster[settlement_raster %in% c(30,23,22,21)] <- 1 # urban\nsettlement_raster[settlement_raster %in% c(13,12,11)] <- 2 # rural\nsettlement_raster[settlement_raster == 10] <- NA #water\n\n# re-plot\nplot(settlement_raster, main = \"Merged settlement categories (GHS-SMOD data)\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThe plot shows our new settlement categories with urban and rural areas categorized as 1 and 2, respectively.\n\nThe final processing step is to increase the spatial resolution of the settlement raster to match the population and administrative unit rasters. We do this using the `terra::resample` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsettlement_raster <- terra::resample(settlement_raster, population_raster, method = \"near\")\n```\n:::\n\n\nSave the three rasters into a folder called \"made\" inside your \"data_wsm\" folder.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check whether the data folder already exists - if not, create the folder \nfile_path <- paste0(getwd(),\"/data_wsm/made/\")\nif (!dir.exists(paste0(file_path))) {\n  dir.create(file_path)\n}\n# save rasters\nterra::writeRaster(admin_raster,paste0(file_path,\"adminGADM.tif\"))\nterra::writeRaster(population_raster,paste0(file_path,\"popWP.tif\"))\nterra::writeRaster(settlement_raster,paste0(file_path,\"settGHS.tif\"))\n```\n:::\n\n\n## gridEZ: sampling frame generation\n\nThe `gridEZ` function has been designed so that you can either apply pre-defined specifications or specify your own. More information on this can be found in the Tutorial Overview. Below we demonstrate both approaches.\n\nIf a sampling frame is being generated for a large geographic area the code will require a significant amount of computer memory. It is therefore good practice to remove R objects not being used and carry out a \"garbage collection\" before we start.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# remove all objects\nrm()\n# garbage collection\ngc()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          used (Mb) gc trigger  (Mb) limit (Mb) max used  (Mb)\nNcells 1682003 89.9    3058031 163.4         NA  3058031 163.4\nVcells 2494422 19.1   10146329  77.5      36864  8669200  66.2\n```\n\n\n:::\n:::\n\n\n`gridEZ` utilises parallel processing to generate EZs for different strata at the same time. The number of parallel jobs that can be executed will depend on your computing system. You can work this out using the following code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# total number of cores available on your computer\nparallel::detectCores() \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n\n```{.r .cell-code}\n# we advise that you use your total number of cores minus 1 but you could use fewer (unless you only acces to one core, then you should specify 1 processing core) \nprocessing_cores <- max(parallel::detectCores() - 1, 1)\nprocessing_cores\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13\n```\n\n\n:::\n:::\n\n\nThe `gridEZ` function reads input rasters straight from file so there is no need to read them into R before executing the function. Instead we define where you would like input rasters to be read in from and also where you would like outputs to be saved. These file pathways can be specified directly in the `gridEZ` function, however, I find it cleaner and easier to define these file pathways as objects with much shorter names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# input\nfile_path_inputs <- paste0(getwd(),\"/data_wsm/made/\")\n\n# output\n# check whether the output folders already exists - if not, create them\nfile_path_outputs_tuts <- paste0(getwd(),\"/results_wsm/\")\nif (!dir.exists(paste0(file_path_outputs_tuts))) {\n  dir.create(file_path_outputs_tuts)\n}\nfile_path_outputs <- paste0(getwd(),\"/results_wsm/tutorial1/\")\nif (!dir.exists(paste0(file_path_outputs))) {\n  dir.create(file_path_outputs)\n}\n```\n:::\n\n\nNow we can create our sampling frame. We'll use the \"large\" EZ specifications so our sampling frame will be made up of EZs with population sizes mostly between 800 and 1,600.\n\nWe’ll generate the same sampling frame with two different approaches to demonstrate the different ways `gridEZ` can be applied: first using the predefined specifications, and then using user-defined specifications.\n\nNote, the `run_ID` parameter is used to name output files and should be different for each new run of the gridEZ function.\n\nOk - let's run `gridEZ` with pre-defined specifications. To do this we set `predefined_EZ_size` as TRUE and `EZ_target_size` as \"large\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gridEZ function to generate sampling frame with large EZs: pre-defined specs\ngridEZ2::gridEZ(population_raster_path = paste0(file_path_inputs,\"popWP.tif\"), \n                strata1_raster_path = paste0(file_path_inputs,\"adminGADM.tif\"), \n                strata2_raster_path = paste0(file_path_inputs,\"settGHS.tif\"),\n                predefined_EZ_size = TRUE, \n                EZ_target_size = \"large\",\n                output_path = paste0(file_path_outputs), \n                run_ID = \"wsm_large\",\n                ncores=processing_cores)\n```\n:::\n\n\nIn this example we are creating a sampling frame made up of \"large\" EZs but you can also produce sampling frames with \"medium\" or \"small\" EZs using the pre-defined `gridEZ` specifications. To do this you would replace \"large\" in the code above with \"medium\" or \"small\".\n\nNow let's run `gridEZ` with user-defined specifications. We do this by setting `predefined_EZ_size` to be FALSE and specifying the parameters `target_pop_per_EZ` and `max_cells_per_EZ`.\n\nNote, that the default for `predefined_EZ_size` is TRUE so if it is not included by the user, `gridEZ` will ignore `target_pop_per_EZ` and `max_cells_per_EZ` and the outputs will have (default) medium sized EZs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gridEZ function to generate sampling frame with large EZs: user-defined specs\ngridEZ2::gridEZ(population_raster_path = paste0(file_path_inputs,\"popWP.tif\"), \n                strata1_raster_path = paste0(file_path_inputs,\"adminGADM.tif\"), \n                strata2_raster_path = paste0(file_path_inputs,\"settGHS.tif\"),\n                predefined_EZ_size = FALSE,\n                target_pop_per_EZ = 1200,\n                max_cells_per_EZ = 2500,\n                output_path = paste0(file_path_outputs), \n                run_ID = \"wsm_large_ownspecs\",\n                ncores=processing_cores)\n```\n:::\n\n\nAs you can see from the code above, the user-defined specifications route offers flexibility as `target_pop_per_EZ` and `max_cells_per_EZ` can be tailored to specific survey needs.\n\nGreat - now we can look at the results!\n\n## Evaluating Gridded Sampling Frames\n\nThe `gridEZ` function produces two output files:\n\n-   .csv with file name beginning \"EZ_Pop_Ncells\\_\". Tabular results for EZs within the sampling frame.\n\n-   .tif (raster) with file name beginning \"EZ_IDs\\_\". Raster of the sampling frame.\n\nLet's start by looking at the outputs for the sampling frame generated using the pre-defined settings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in EZs table of your sampling frame \nEZ_tab <- read.csv(paste0(file_path_outputs, \"EZ_Pop_Ncells_wsm_large.csv\"),header=T)\n# number of EZs in your sampling frame\nnrow(EZ_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 305\n```\n\n\n:::\n\n```{.r .cell-code}\n# the first rows\nhead(EZ_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  EZ_ID       pop    N\n1     1  947.8968  200\n2     2 1257.4823  200\n3     3 1163.7940  217\n4     4  908.7108  492\n5     5  967.2034 1508\n6     6  923.8834  668\n```\n\n\n:::\n:::\n\n\nEach row of the table gives the results for each EZ. There are 305 rows, i.e. 305 EZs in the sampling frame. From the top row, we know that the focal EZ has an ID of 1, a population size of 948, and contains 200 grid cells.\n\nTo check that the sampling frame generated using the user-defined settings is the same, we can compare EZ tables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in EZs table of your sampling frame \nEZ_tab_ownspecs <- read.csv(paste0(file_path_outputs, \"EZ_Pop_Ncells_wsm_large_ownspecs.csv\"),header=T)\n# number of EZs in your sampling frame\nnrow(EZ_tab_ownspecs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 305\n```\n\n\n:::\n\n```{.r .cell-code}\n# the first rows\nhead(EZ_tab_ownspecs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  EZ_ID       pop    N\n1     1  947.8968  200\n2     2 1257.4823  200\n3     3 1163.7940  217\n4     4  908.7108  492\n5     5  967.2034 1508\n6     6  923.8834  668\n```\n\n\n:::\n:::\n\n\nFrom this we can see that the same sampling frame has been made. The goal of creating the two sampling frames was to demonstrate the two different approached. Now you have everything you need to start creating sampling frames using a variety of target EZ sizes.\n\nLet's carry on evaluating our sampling frame (we could use either pre- or user-defined outputs here). First, we'll create a map of the EZs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in your sampling frame raster & plot\nEZ <- terra::rast(paste0(file_path_outputs,\"EZ_IDs_wsm_large.tif\"))\n\n# simple plot\n# convert to sf polygons\nres_poly <- terra::as.polygons(EZ, dissolve = TRUE)\nres_poly <- sf::st_as_sf(res_poly)\n# merge the ppolygons and EZ IDs\nres_poly <- merge(res_poly,EZ_tab,by=\"EZ_ID\")\n# plot EZ polygons coloured by EZ IDs\nplot(res_poly[,\"geometry\"],main=\"Spatial distribution of EZs\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nThe plot above shows the EZ boundaries. Now let's look at the population sizes of the EZs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot EZ polygons coloured by population per EZ\nplot(res_poly[,\"pop\"],main=\"EZ population size\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nEZs with relatively low population size are located in the centre of the islands where the population is sparse. But if we had a target population per EZ, shouldn't all the EZs be within the desirable range of 800-1600 for the \"large\" EZ setting? No - because we also have a maximum geographic size per EZ too! Let's map the number of grid cells per EZ.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot EZ polygons coloured by number of grid cells per EZ\nplot(res_poly[,\"N\"],main=\"EZ grid cells count\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nThe maximum geographic size per EZ for the large EZ setting is 2,500 grid cells. However, `gridEZ` allows blocks up to 1.5 times the value given for the maximum geographic size to be accepted as an EZ. So in our example this is 3,750. The `gridEZ` function allows this leeway above the ideal maximum geographic size per EZ because the requirement to create compact shapes restricts how the algorithm can combine/split blocks of grid cells. Without this extra flexibility, we’d end up with many EZs much smaller than the maximum geographic size that also have low population counts - two undesirable traits. It is better for an EZ to be slightly larger in geographic size if that helps keep its population closer to the target.\n\nIf a survey design requires a very strict maximum geographic size of survey units, the `max_cells_per_EZ` parameter can be adjusted accordingly, e.g. if the hard limit is 1,500 grid cells, the user could set `max_cells_per_EZ` to be 1,000. In this case, most sparsely populated EZs would have sizes close to 1,000 cells and only some would have sizes close to 1,500.\n\nNow that we've looked at the spatial distribution of population and grid cells per EZ, let's create a scatter plot to look at the two EZ characteristics together.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(res_poly, aes(x = N, y = pop)) +\n  \n  # grey scatter plot area for values within acceptable values\n  annotate(\"rect\",\n           xmin = 0, xmax = 3750,\n           ymin = 800, ymax = 1600,\n           fill = \"grey30\", alpha = 0.2) +\n  \n  annotate(\"rect\",\n           xmin = 1875, xmax = 3750,\n           ymin = 0, ymax = 800,\n           fill = \"grey30\", alpha = 0.2) +\n  \n  geom_point(alpha = 0.7, size = 3) +\n  \n  # include threshold lines\n  geom_hline(yintercept = c(800, 1600),\n             colour = \"red\", linetype = \"dashed\") +\n  geom_vline(xintercept = c(1875, 3750),\n             colour = \"blue\", linetype = \"dashed\") +\n  \n  theme_minimal() +\n  labs(\n    x = \"grid cells per EZ\",\n    y = \"pop count per EZ\",\n    title = \"\"\n  )\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nThe red horizontal lines indicate the desirable range for population per EZ and the blue vertical lines show the acceptable geographic size range for EZs with undesirably low population. You can see that no EZs are geographically larger than the acceptable maximum grid cells per EZ of 3,750. Therefore, all the EZs that fall between the red horizontal lines meet our criteria for ideal EZs (n = 169). The EZs that fall between the blue vertical lines but below the lower red horizontal line have a desirable geographic size given that they are located in sparsely populated areas. These are acceptable EZs (n=83). Generally, all EZs sitting outside of these areas on the scatter plot, (i.e. outside of the grey areas), are not considered to be acceptable EZs given our criteria.\n\nHowever, there are a number of restrictions that may lead to the criteria not being met. One example is when a single grid cell has population size greater than the upper end of the desirable population range, e.g. in densely populated areas of cities. The grid based nature of our algorithm means that we can not split individual grid cells and so these become individual EZs. On the scatter plot these EZs would be plotted on the far left (1 grid cell per EZ) above the upper red horizontal line. We can see from our scatter plot that, in this example, there are no single cell EZs with population size greater than 1,600 so no EZs fall into this category.\n\nFor our sampling frame, let's investigate all the EZs outside of the grey areas on our scatter plot. To help with this, we can categorize the EZs by where they sit on the scatter plot using the following code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_poly$cat <- NA\n# category 1: meets pop and geog criteria \nres_poly$cat[res_poly$N<=3750 & res_poly$pop>=800 & res_poly$pop<=1600] <- 1\n# category 2: low pop but meets max geog range\nres_poly$cat[res_poly$N>=1875 & res_poly$N<=3750 & res_poly$pop<800] <- 2\n# category 3: high pop but only 1 cell\nres_poly$cat[res_poly$N==1 & res_poly$pop>1600] <-3\n# category 4: below max geog range but over pop max and has more than 1 cell\nres_poly$cat[res_poly$N>1 & res_poly$pop>1600] <- 4\n# category 5: pop & cell count are too low\nres_poly$cat[res_poly$N<1875 & res_poly$pop<800] <- 5\n\nres_poly$cat <- as.factor(res_poly$cat)\n\n# re-do scatter plot colour coded by category\n\n# define the colour coding first\ncat_cols <- scales::hue_pal()(5)\n\nggplot(res_poly, aes(x = N, y = pop, colour = cat)) +\n  geom_point(size = 3, alpha = 0.8) +\n  scale_colour_manual(values = cat_cols) +\n  theme_minimal() +\n  labs(\n    x = \"grid cells per EZ\",\n    y = \"pop count per EZ\",\n    colour = \"Category\",\n    title = \"\"\n  )\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nCateogories 1 and 2 correspond to the EZs we described above. Category 3 corresponds to single celled EZs with high population counts - as mentioned, we don't have any in this Samoa example. Category 4 consists of EZs whose population size is too big based on our criteria and category 5 consists of EZs whose population size is too small based on our criteria. Let's count the EZs in each category:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(res_poly$cat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   4   5 \n169  83   5  48 \n```\n\n\n:::\n:::\n\n\nThere are 252 EZs that fall into categories 1 and 2 out of a total of 305 EZs in our sampling frame (i.e. 83%. of all our EZs). There are 5 EZs in category 4 and 48 EZs in category 5. We can map the EZs by category to see where they are located.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(res_poly[\"cat\"], pal = cat_cols, main=\"EZs by evaluation category\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nStraight away we can easily see a handful of EZs in category 5. Given their category, can you guess which points in the scatter plot correspond to these? Hint: their geographic size is only slightly below the target grid cells per EZ for sparsely populated areas. Of greater concern are the EZs that are very small in both population and geographic size. Let's zoom in on an area to take a closer look.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# zoomed in map\nplot(res_poly[\"cat\"], pal = cat_cols,ylim=c(-13.96,-13.77),xlim=c(-172.27,-171.95), main=\"EZs by evaluation category - zoomed in\")\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nSamoa consists of two main island - Savai'i in the west and Upolu in the east - and many smaller islands. Here we see a tiny island situated between the two main islands that has a single EZ which is in category 5, i.e. population smaller than the target EZ population size. It is generally preferable to have EZs be contiguous in space so that survey field teams do not need to travel through non-survey unit areas to cover a whole unit. The `gridEZ` algorithm therefore enforces spatial contiguity for EZs. This results in small islands like this one being one single EZ - in most survey designs, this is preferable over several islands being part of the same EZ.\n\nNow let's focus on the section of Upolu that we see in the above map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# zoom in more and use ggplot\n\n# define the categories plot\np1 <- ggplot(res_poly) +\n  geom_sf(aes(fill = cat), colour = \"black\", linewidth = 0.4) +\n  scale_fill_manual(values = cat_cols) +   # same palette as before\n  coord_sf(\n    xlim = c(-172.08, -171.98),\n    ylim = c(-13.95, -13.82),\n    expand = FALSE\n  ) +\n  theme_minimal() +\n  labs(\n    fill = \"Category\",\n    x = \"Longitude\",\n    y = \"Latitude\",\n    title = \"\"\n  )\n\n# read in the settlement raster and admin polygons\nsettlement_raster <- terra::rast(paste0(file_path_inputs,\"settGHS.tif\"))\nadmin_sf <- sf::st_read(paste0(getwd(),\"/data_WSM/gadm41_WSM_shp/gadm41_WSM_2.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `gadm41_WSM_2' from data source \n  `/Users/clairedooley/Documents/Research/gridEZ/gridEZ_tutorials/data_wsm/gadm41_WSM_shp/gadm41_WSM_2.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 43 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -172.8041 ymin: -14.07722 xmax: -171.3977 ymax: -13.43981\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# plot these survey strata\n# convert the raster into a data.frame first\nsettlement_df <- as.data.frame(settlement_raster, xy = TRUE, na.rm = FALSE)\nsettlement_df$GHS_SMOD_E2025_GLOBE_R2023A_54009_1000_V2_0_R11_C2 <- as.factor(settlement_df$GHS_SMOD_E2025_GLOBE_R2023A_54009_1000_V2_0_R11_C2)\n# define strata plot\np2 <- ggplot() +\n  geom_raster(data = settlement_df, aes(x = x, y = y, fill = GHS_SMOD_E2025_GLOBE_R2023A_54009_1000_V2_0_R11_C2)) +\n  geom_sf(data = admin_sf, fill = NA, colour = \"black\", linewidth = 0.7) +\n  scale_fill_scico_d(palette = \"nuuk\", na.value = \"transparent\") +\n  coord_sf(\n    xlim = c(-172.08, -171.98),\n    ylim = c(-13.95, -13.82),\n    expand = FALSE\n  ) +\n  theme_minimal() +\n  labs(\n    fill = \"Value\",\n    x = \"Longitude\",\n    y = \"Latitude\",\n    title = \"\"\n  )\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nIn the left hand plot we see several category 5 EZs. The right hand plot shows our two strata layers. The overall spatial stratification for the sampling frame is a combination of the two, i.e. stratum 1 = settlement type 1 in admin unit A; stratum 2 = settlement type 2 in admin unit A; stratum 3 = settlement type 1 in admin unit B; stratum 4 = settlement type 2 in admin unit B; etc. The overall spatial stratification delineates what we consider \"uncrossable\" boundaries and `gridEZ` therefore does not allow EZs to cross different strata. EZs are always contained within one stratum. This stratification approach is important for survey design but can lead to EZs with small population and small geograhpic size, depending on how the layers used to define the overall stratification intersect with one another. In our example, the overall stratification based on GHS-SMOD and GADM administrative units essentially consists of little psuedo islands within the landmass and explains most of the category 5 EZs that we see in the left hand plot above.\n\nThe `gridEZ` algorithm balances compactness of EZ shapes against meeting the population and geographic criteria. In several cases, this can lead to a decision not to add or split a block of grid cells and instead call it good as an EZ. This is the likely explanation for the remaining EZs in categories 4 and 5.\n\n## Creation of table for survey sample selection\n\nSurveys require a table of survey sampling frame units (here, these are EZs) to sample from. We currently have a table of EZs and their population counts, but as many surveys will want to sample a specific number of units per stratum (stratified sampling) we need to add the corresponding stratum for each EZ.\n\nWe can do this by spatially linking the EZ IDs raster with the two strata rasters. The result is a table containing the information from the three rasters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in the strata raster\nadmin_raster <- terra::rast(paste0(file_path_inputs,\"adminGADM.tif\"))\nsettlement_raster <- terra::rast(paste0(file_path_inputs,\"settGHS.tif\"))\n\n# the extent of the EZ raster is defined by the presence of EZs and may be different to the extent of the input files which was set by the population raster\n# remember EZs are created for grid cells with non-NA values across all 3 input rasters, not everywhere there is population\n# because of this we extend the EZ raster to match the input rasters\nEZ <- terra::extend(EZ,admin_raster)\n\n# create a table of EZ strata values\n\n# we need to create a table with vectors of values in each raster\n# as the admin_raster contains categories, we want the category labels rather than their corresponding numeric value\nadmin_cats <- terra::cats(admin_raster)[[1]]\nadmin_labels <- admin_cats[match(admin_raster[], admin_cats[,1]),2]\n# as we defined the distance categories by numeric values, we can directly use those raster values\nEZ_strata <- data.table::data.table(EZ[],\n                                    admin_labels,\n                                    settlement_raster[])\n# set column names, change as needed\nnames(EZ_strata) <- c(\"EZ_ID\",\"strata1\",\"strata2\") \n# reduce table down to a single row per EZ\nEZ_strata <- na.omit(EZ_strata)\nEZ_strata <- unique(EZ_strata)\n```\n:::\n\n\nLet's have a look at the top of the table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# look at the top of the table\nhead(EZ_strata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   EZ_ID   strata1 strata2\n   <num>    <char>   <num>\n1:    98 WSM.5.4_1       2\n2:    96 WSM.5.3_1       2\n3:   100 WSM.6.1_1       2\n4:   105 WSM.6.2_1       2\n5:   101 WSM.6.1_1       2\n6:    99 WSM.5.4_1       2\n```\n\n\n:::\n:::\n\n\nGreat - looks good. Now we can merge it with our EZ table that we read in from the .csv file produced by `gridEZ` so that we have EZ population and strata information all in one table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# merge\nEZ_tab <- merge(EZ_tab,EZ_strata,by=\"EZ_ID\")\n# check number of rows/EZs\nnrow(EZ_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 305\n```\n\n\n:::\n\n```{.r .cell-code}\n# look at the top of the table\nhead(EZ_tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  EZ_ID       pop    N   strata1 strata2\n1     1  947.8968  200 WSM.1.1_1       1\n2     2 1257.4823  200 WSM.1.1_1       1\n3     3 1163.7940  217 WSM.1.1_1       1\n4     4  908.7108  492 WSM.1.1_1       2\n5     5  967.2034 1508 WSM.1.1_1       2\n6     6  923.8834  668 WSM.1.1_1       2\n```\n\n\n:::\n:::\n\n\nExcellent - now we have a table with the following characteristic for each EZ in our sampling frame:\n\n-   ID\n\n-   population count\n\n-   grid cell count\n\n-   ID of strata 1 (administrative unit)\n\n-   ID of strata 2 (settlement category)\n\nFinally, it may be useful to count the EZs in each strata. We can summarise this in a table as follows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(EZ_tab$strata1,EZ_tab$strata2)\n```\n:::\n\n\nFor visual inspection we can also plot it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(EZ_tab, aes(x = strata1, fill = as.factor(strata2))) +\n  geom_bar(position = \"stack\") +\n  labs(\n    title = \"Count of EZs per stratum\",\n    x = \"Admin. unit\",\n    y = \"Count\",\n    fill = \"Settlement type\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)\n  ) +\n  scale_fill_discrete(labels = c(\"1\" = \"urban\", \"2\" = \"rural\"))\n```\n\n::: {.cell-output-display}\n![](gridEZ_tutorial1_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n## Summary\n\nThis tutorial has covered:\n\n-   preparing example datasets suitable for the `gridEZ` R function\n\n-   generating gridded sampling frames using two `gridEZ` options:\n\n    1.  applying pre-defined specifications\n\n    2.  applying user-defined specifications\n\n-   summarising output sampling frames\n\n-   evaluating sampling frame EZs\n\n-   creating a table suitable for survey sample selection, i.e. containing EZ ID, population count and strata IDs\n\n## Feedback\n\nWe are very interested to know:\n\n-   how survey practitioners, researchers and data collectors are using gridEZ\n\n-   how these tutorials can be updated or improved\n\nPlease use the link below to provide any comments or feedback.\n\n<a id=\"feedback-link\" class=\"btn btn-dark\" target=\"_blank\">Give feedback</a>\n\n```{=html}\n<script>\ndocument.addEventListener(\"DOMContentLoaded\", function() {\n  // Your Google Form URL\n  const base = \"https://docs.google.com/forms/d/e/1FAIpQLSdOokaez2GCTBqDzOOJbqTxU2ydZU5TvzW7oO75BhVMnPo8Iw/viewform?usp=pp_url&entry.1982908603=\";\n\n  // Make sure the element exists\n  const link = document.getElementById(\"feedback-link\");\n  if (link) {\n    // Set the href dynamically\n    link.setAttribute(\"href\", base + encodeURIComponent(window.location.href));\n  }\n});\n</script>\n```\n",
    "supporting": [
      "gridEZ_tutorial1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}